frameworks:
  interactive:
    nextjs:
      name: "Next.js"
      description: "React framework for production"
      routers: ["app", "pages"]
      features: ["typescript", "tailwind", "prisma", "t3", "shadcn"]
      default_features: ["typescript", "tailwind"]
      feature_descriptions:
        typescript: "Add TypeScript support"
        tailwind: "Add Tailwind CSS for styling"
        prisma: "Add Prisma ORM with PostgreSQL"
        t3: "Add T3 Stack (tRPC + NextAuth + Prisma + Tailwind)"
        shadcn: "Add shadcn/ui component library (with a Button example)"

    reactjs:
      name: "React"
      description: "JavaScript library for building user interfaces"
      features: ["typescript", "tailwind"]
      default_features: ["typescript", "tailwind"]
      feature_descriptions:
        typescript: "Add TypeScript support"
        tailwind: "Add Tailwind CSS for styling"

    astrojs:
      name: "Astro"
      description: "Static site generator for modern web projects"

  simple:
    express:
      name: "Express.js"
      description: "Fast, unopinionated web framework for Node.js"
      databases: ["none", "mongodb", "postgresql", "supabase"]
      default_database: "none"
      database_descriptions:
        none: "No database (basic Express setup)"
        mongodb: "MongoDB with Mongoose ODM"
        postgresql: "PostgreSQL with Sequelize ORM"
        supabase: "Supabase (PostgreSQL with real-time features)"

    flask:
      name: "Flask"
      description: "Lightweight WSGI web application framework"

    django:
      name: "Django"
      description: "The web framework for perfectionists with deadlines"

    svelte:
      name: "Svelte"
      description: "Cybernetically enhanced web apps"

    strapi:
      name: "Strapi"
      description: "Headless CMS to build powerful APIs with no effort"

    serverless:
      name: "Serverless"
      description: "Serverless application template (AWS Lambda, etc.)"
      languages: ["javascript", "typescript", "python", "go"]
      default_language: "javascript"
      language_descriptions:
        javascript: "Node.js (JavaScript) runtime for AWS Lambda, etc."
        typescript: "TypeScript runtime for AWS Lambda, etc."
        python: "Python 3.x runtime for AWS Lambda, etc."
        go: "Go 1.x runtime for AWS Lambda, etc."

presets:
  mern:
    name: "MERN Fullstack"
    description: "MongoDB, Express, React, Node.js fullstack boilerplate"
    frontend:
      framework: "reactjs"
      features: ["typescript", "tailwind"]
      directory: "client"
    backend:
      framework: "express"
      features: ["mongodb"]
      directory: "server"

  nextjs-fullstack:
    name: "Next.js Fullstack"
    description: "Next.js with Prisma ORM and PostgreSQL fullstack boilerplate"
    frontend:
      framework: "nextjs"
      features: ["app", "typescript", "tailwind", "prisma"]
      directory: "."

  t3:
    name: "T3 Stack"
    description: "TypeScript + Next.js + Prisma + tRPC + NextAuth + Tailwind fullstack boilerplate"
    frontend:
      framework: "nextjs"
      features: ["app", "typescript", "tailwind", "t3"]
      directory: "."

  headless-cms:
    name: "Headless CMS (Next.js + Strapi)"
    description: "Next.js frontend with Strapi CMS backend for modern headless architecture"
    frontend:
      framework: "nextjs"
      features: ["app", "typescript", "tailwind"]
      directory: "frontend"
    backend:
      framework: "strapi"
      features: []
      directory: "cms"

ui:
  welcome_message: "Welcome to AppGen!"
  welcome_subtitle: "Let's create your next project together."
  default_project_name: "my-project"
  colors:
    primary: "cyan"
    secondary: "magenta"
    success: "green"
    warning: "yellow"
    error: "red"

templates:
  base_path: "templates"
  auto_cleanup: true
  merge_package_json: true
